sudo: false
language: python
addons:
  postgresql: 9.3

env:
  global:
    - POSTGRESQL_DSN=postgresql://postgres@localhost/sqlalchemy_defaults_test
    - MYSQL_DSN=mysql+pymysql://travis@localhost/sqlalchemy_defaults_test

before_script:
  - psql -c 'create database sqlalchemy_defaults_test;' -U postgres
  - mysql -e 'create database sqlalchemy_defaults_test;'

matrix:
  include:
  - python: 2.6
    env:
      - 'TOXENV="py26-{sqlite,postgresql,mysql}"'
  - python: 2.7
    env:
      - 'TOXENV="py27-{sqlite,postgresql,mysql}"'
  - python: 3.3
    env:
      - 'TOXENV="py33-{sqlite,postgresql,mysql}"'
  - python: 3.4
    env:
      - 'TOXENV="py34-{sqlite,postgresql,mysql}"'
  - python: 3.5
    env:
      - 'TOXENV="py35-{sqlite,postgresql,mysql}"'
  - python: 2.7
    env:
      - "TOXENV=lint"

install:
  - pip install tox

script:
  - tox
